### ISSUE TITLE
Windows build fails because of deprecated behaviors CMP0042 and CMP0054

### ISSUE THREAD

**Issue by gillesdegottex** [roebel/EASDIF_SDIF#2]
This log might be useful:
[log.txt](https://github.com/roebel/EASDIF_SDIF/files/1998916/log.txt)
visible also here:
https://ci.appveyor.com/project/gillesdegottex/dfasma/build/1.0.761/job/2ju0b762omruoasf

**Comment by roebel** [comment]
Please see here at the end for a successful configuration of EASDIF_SDIF with cmake 3.8.0
It does not emit the smallest warning because all policies are correctly set.

If it does fail with your cmake 3.0.2 on your windows build than this cannot possibly be due to 
the fact that the cmake modes are no longer supported as they are  processed with any warning in a cmake version that is much more recent than the one you use.

>  The cmake-policies(7) manual explains that the OLD behaviors of all
>  policies are deprecated and that a policy should be set to OLD only under
>  specific short-term circumstances.  Projects should be ported to the NEW 
> behavior and not rely on setting a policy to OLD.

I don't remember this exactly but it might be that cmake 3.0.2 this was the policy with policies, today the documentation says that policies are used to:

>Tell CMake to use the OLD or NEW behavior for a given policy. Projects depending on the old >behavior of a given policy may silence a policy warning by setting the policy state to OLD. >Alternatively one may fix the project to work with the new behavior and set the policy state to >NEW.

For the two policies you mentioned I find in the documentation

CMP0042
This policy was introduced in CMake version 3.0.  CMake version
3.8.1 warns when the policy is not set and uses OLD behavior.  Use
the cmake_policy command to set it to OLD or NEW explicitly.

CMP0054
This policy was introduced in CMake version 3.1.
CMake version 3.8.1 warns when the policy is not set and uses
``OLD`` behavior.  Use the ``cmake_policy()`` command to set
it to ``OLD`` or ``NEW`` explicitly.

That means both policies are still supported in old version in 3.8.0 and I can not tell you why it fails in your compilation. May be try a different cmake version ?

Best
Axel


$> cmake ../ -DEASDIF_BUILD_STATIC:BOOL=1
-- The C compiler identification is AppleClang 8.0.0.8000042
-- The CXX compiler identification is AppleClang 8.0.0.8000042
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ===============================================================
-- == Configuring Easdif   1.4.26
-- ===============================================================
-- configure for architecture x86_64, CMAKE PROCESSOR = x86_64 HOST PROCESSOR = x86_64
-- Configure for mode = release
-- configure for architecture x86_64, CMAKE PROCESSOR = x86_64 HOST PROCESSOR = x86_64
-- configure for architecture x86_64, CMAKE PROCESSOR = x86_64 HOST PROCESSOR = x86_64
-- CHECK FOR HEADERS
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for stdarg.h
-- Looking for stdarg.h - found
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for float.h
-- Looking for float.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for errno.h
-- Looking for errno.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for getenv
-- Looking for getenv - found
-- Looking for ftruncate
-- Looking for ftruncate - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- PARTICULAR COMPILER CHARACTERISTICS
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of long
-- Check size of long - done
-- Sizeof type long is  8!
-- Looking for C++ include sstream
-- Looking for C++ include sstream - found
-- Looking for C++ include strstream
-- Looking for C++ include strstream - found
-- ===============================================================
-- == Configuring SDIF   3.11.6
-- ===============================================================
-- configure for architecture x86_64, CMAKE PROCESSOR = x86_64 HOST PROCESSOR = x86_64
-- CHECK FOR HEADERS
-- PARTICULAR COMPILER CHARACTERISTICS
-- Looking for machine/endian.h
-- Looking for machine/endian.h - found
-- Sizeof type long is  8!
-- Writing sdif config
-- Check size of int64_t
-- Check size of int64_t - done
-- Sizeof type int64_t is  8!
-- Check size of __int64
-- Check size of __int64 - failed
-- Sizeof type __int64 is  0!
-- Check size of INT64
-- Check size of INT64 - failed
-- Sizeof type INT64 is  0!
-- Check size of long long
-- Check size of long long - done
-- Sizeof type long long is  8!
-- Check size of loff_t
-- Check size of loff_t - failed
-- Sizeof type loff_t is  0!
-- Check size of off64_t
-- Check size of off64_t - failed
-- Sizeof type off64_t is  0!
-- Check size of off_t
-- Check size of off_t - done
-- Sizeof type off_t is  8!
-- use 64bit type int64_t
-- Writing Easdif config
-- ===================================================================
-- Option summary:
-- install prefix (CMAKE_INSTALL_PREFIX)         : /u/formes/share
-- enable swig python interf. (EASDIF_DO_PYTHON) : OFF
-- enable swig perl interface (EASDIF_DO_PERL)   : OFF
-- enable swig java interface (EASDIF_DO_JAVA)   : OFF
-- build static Easdif lib (EASDIF_BUILD_STATIC) : 1
-- build static sdif lib (SDIF_BUILD_STATIC)     : OFF
-- enable thread support (USE_THREADS)           : ON
-- build mex files (EASDIF_BUILD_MEX)            : OFF
-- enable universal (DOUNIVERSAL)                :
-- Easdif installation summary:
-- bin            : /u/formes/share/bin/Darwin_x86_64
-- lib            : /u/formes/share/lib/Darwin_x86_64
-- includes       : /u/formes/share/include
-- pkgconfig      : /u/formes/share/lib/Darwin_x86_64/pkgconfig
-- ===================================================================
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/roebel/tmp/EASDIF_SDIF/build

**Comment by gillesdegottex** [comment]
Compiled smoothly with cmake 3.8.0 :)

https://ci.appveyor.com/project/gillesdegottex/dfasma/build/1.0.806/job/r7gtic7c3udir2r8

Thanks for the feedback!
